security:
    factories:
          - "%kernel.root_dir%/../vendor/bundles/FOS/FacebookBundle/Resources/config/security_factories.xml"
          
    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
          # choose the provider name freely
          facebook_provider:
              id: facebook.user_provider
          fos_userbundle:
            id: fos_user.user_manager
                
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        public:
            pattern: ^/*
            fos_facebook:
                app_url: "http://apps.facebook.com/mytubonet/"
                server_url: "http://tubo.zapto.org/app_dev.php/"
                login_path: /login
                check_path: /login_check
                default_target_path: /
                provider: facebook_provider
            anonymous: true
            logout:
                handlers: ["fos_facebook.logout_handler"]

    access_control:
        - { path: ^/login$, role: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/.*, role: [IS_AUTHENTICATED_FULLY] }